LANGUAGES = {
    "auto": "Auto Detect",
    "en": "English",
    "ko": "Korean",
    "ja": "Japanese",
    "zh-CN": "Chinese (Simplified)",
    "zh-TW": "Chinese (Traditional)",
    "fr": "French",
    "de": "German",
    "es": "Spanish",
    "ru": "Russian",
    "it": "Italian",
    "pt": "Portuguese",
    "vi": "Vietnamese",
    "id": "Indonesian",
    "th": "Thai",
    "ar": "Arabic",
    "hi": "Hindi",
    "tr": "Turkish",
    "pl": "Polish",
    "nl": "Dutch",
    "sv": "Swedish",
    "fi": "Finnish",
    "no": "Norwegian",
    "da": "Danish",
    "cs": "Czech",
    "hu": "Hungarian",
    "he": "Hebrew",
    "el": "Greek",
    "ro": "Romanian",
    "sk": "Slovak",
    "uk": "Ukrainian",
    "bg": "Bulgarian",
    "hr": "Croatian",
    "sr": "Serbian",
    "fa": "Persian",
    "ms": "Malay",
    "tl": "Tagalog",
    "et": "Estonian",
    "lv": "Latvian",
    "lt": "Lithuanian",
    "sl": "Slovenian",
    "mt": "Maltese",
    "ga": "Irish",
    "sq": "Albanian",
    "mk": "Macedonian",
    "af": "Afrikaans",
    "sw": "Swahili",
    "zu": "Zulu",
    "xh": "Xhosa",
    "st": "Southern Sotho",
    "tn": "Tswana",
    "ts": "Tsonga",
    "ss": "Swati",
    "ve": "Venda",
    "nr": "South Ndebele",
    "nso": "Northern Sotho",
    "kg": "Kongo",
    "rw": "Kinyarwanda",
    "so": "Somali",
    "yo": "Yoruba",
    "ig": "Igbo",
    "ha": "Hausa",
    "am": "Amharic",
    "om": "Oromo",
    "ti": "Tigrinya",
    "sn": "Shona",
    "ny": "Chichewa",
    "mg": "Malagasy",
    "rn": "Kirundi",
    "ln": "Lingala",
    "lu": "Luba-Katanga",
    "to": "Tonga",
}
